version: '3.9'

services:
  backend:
    build: .
    container_name: lupon_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.42
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.1.42:5173
      - CSRF_TRUSTED_ORIGINS=http://localhost:5173,http://192.168.1.42:5173
    volumes:
      - .:/app
